[build]
target-dir = "C:\\temp\\unidoc-target"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = 0 }
complexity = { level = "warn", priority = 0 }
perf = { level = "warn", priority = 0 }
style = { level = "warn", priority = 0 }
pedantic = { level = "allow", priority = 0 }
nursery = { level = "allow", priority = 0 }

needless_pass_by_value = "allow"
too_many_arguments = "allow"
type_complexity = "allow"
large_stack_frames = "allow"
result_large_err = "allow"
